// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUkgEHUlMMPn_h4Fi1tubLL6eIXmJdQY',
    appId: '1:402819546909:web:eaba9e0bbbb0374436abf4',
    messagingSenderId: '402819546909',
    projectId: 'mr-automotive-8fbfa',
    authDomain: 'mr-automotive-8fbfa.firebaseapp.com',
    storageBucket: 'mr-automotive-8fbfa.appspot.com',
    measurementId: 'G-3S6W93DSHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwA_0Mh1OfT52k3jqh6i1I07WNriA2kU',
    appId: '1:402819546909:android:c4f71d283183c1a036abf4',
    messagingSenderId: '402819546909',
    projectId: 'mr-automotive-8fbfa',
    storageBucket: 'mr-automotive-8fbfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7BRr8ZWNCxyJP9AaEmxmVzJ4Bk20R2xk',
    appId: '1:402819546909:ios:d8f0e55f388fe9db36abf4',
    messagingSenderId: '402819546909',
    projectId: 'mr-automotive-8fbfa',
    storageBucket: 'mr-automotive-8fbfa.appspot.com',
    iosBundleId: 'com.dev.automotive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7BRr8ZWNCxyJP9AaEmxmVzJ4Bk20R2xk',
    appId: '1:402819546909:ios:02d28aa50025525636abf4',
    messagingSenderId: '402819546909',
    projectId: 'mr-automotive-8fbfa',
    storageBucket: 'mr-automotive-8fbfa.appspot.com',
    iosBundleId: 'com.dev.automotive.RunnerTests',
  );
}
